services:
  - type: static
    name: vite-frontend
    repo: https://github.com/godofwar64/restaurant-main.git
    buildCommand: npm install && npm run build
    publishCommand: ""
    publishDir: frontend/dist
    root: frontend
